name: C/C++ CI

on: 
  push:
  pull_request:

jobs:
  ubuntu-build:
    runs-on: ubuntu-18.04
    steps:
        #- name: Checkout
        # uses: actions/checkout@v2.0.0
    - name: announce
      run: echo "Building CBC branch ${GITHUB_REF##*/}"
    - name: dependencies
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test ; sudo apt-get update ; sudo apt-get install gcc-9 libgcc-9-dev g++-9 gfortran-9 libgfortran-9-dev liblapack-dev libsuitesparse-dev libmetis-dev libnauty2-dev ; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90 ; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 ; sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-9 90 ; sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-9 90
    - name: CoinBrew fetch
      run: wget -nH https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew  ; chmod u+x coinbrew ; ./coinbrew fetch Cbc:${GITHUB_REF##*/} --no-prompt
    - name: Build
      run: ./coinbrew build --prefix=/home/runner/prog Cbc:${GITHUB_REF##*/} --no-prompt --verbosity=4 --disable-shared --enable-static --fully-static --parallel-jobs=2 --tests none
    - uses: actions/upload-artifact@v2
      with:
        name: cbc-x86-64-linux-gcc9.zip
        path: /home/runner/prog/
